name: namemeanning
description: Name Meanning.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http:
  html:
  font_awesome_flutter: ^8.5.0
  auto_size_text:
  launch_review:
  admob_flutter: ^0.3.4
  firebase_admob:
  url_launcher:



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
